import Entitler
import Foundation

/// The access level of the generated `Features` enum and its constants.
public enum AccessLevel: String, CaseIterable, Sendable {
  /// `public`, for a feature module other modules import.
  case `public`
  /// `package`, for a package's own modules.
  case package
  /// `internal`, the default.
  case `internal`
}

/// The initialisms names keep in upper case, after the API Design Guidelines: `export_pdf` becomes
/// `exportPDF` and `support_sla_hours` becomes `supportSLAHours`. At the start of a name they are
/// lower case: `api_calls` becomes `apiCalls`.
public let featureNameInitialisms: Set<String> = [
  "ai", "api", "csv", "html", "http", "https", "id", "ip", "json", "pdf", "sdk", "sku", "sla", "sms",
  "sql", "sso", "ui", "url", "uuid", "xml",
]

private let reservedWords: Set<String> = [
  "any", "as", "associatedtype", "await", "break", "case", "catch", "class", "continue", "default",
  "defer", "deinit", "do", "else", "enum", "extension", "fallthrough", "false", "fileprivate", "for",
  "func", "guard", "if", "import", "in", "init", "inout", "internal", "is", "let", "nil", "open",
  "operator", "package", "private", "precedencegroup", "protocol", "public", "repeat", "rethrows",
  "return", "self", "some", "static", "struct", "subscript", "super", "switch", "throw", "throws",
  "true", "try", "typealias", "var", "where", "while",
]

/// The Swift name for a feature key: lower camel case, with ``featureNameInitialisms`` upper case.
public func featureConstantName(for key: String) -> String {
  key.split(separator: "_").enumerated().map { index, word in
    let word = word.lowercased()
    if index == 0 { return word }
    return featureNameInitialisms.contains(word) ? word.uppercased() : word.prefix(1).uppercased() + word.dropFirst()
  }.joined()
}

/// The names an existing generated file gives each key, so regenerating never renames a constant.
public func existingFeatureNames(in source: String) -> [String: String] {
  let pattern = #"static let `?([A-Za-z_][A-Za-z0-9_]*)`?\s*=\s*(?:Feature<\w+>\(\s*)?"([a-z][a-z0-9_]*)""#
  guard let regex = try? NSRegularExpression(pattern: pattern) else { return [:] }
  var names: [String: String] = [:]
  let range = NSRange(source.startIndex..., in: source)
  for match in regex.matches(in: source, range: range) {
    guard let name = Range(match.range(at: 1), in: source), let key = Range(match.range(at: 2), in: source)
    else { continue }
    names[String(source[key])] = String(source[name])
  }
  return names
}

/// Renders the Swift source of typed feature constants, as `entitler generate` writes it.
///
/// - Parameters:
///   - list: The features, from ``EntitlerServer/features(timeout:)``.
///   - accessLevel: The access level of `Features` and its constants.
///   - existingSource: The file being replaced, whose names are kept for the keys it holds.
public func renderFeatures(
  _ list: FeatureList, accessLevel: AccessLevel = .internal, existingSource: String? = nil
) -> String {
  let features = list.features.sorted { $0.key < $1.key }
  let byKey = Dictionary(features.map { ($0.key, $0) }, uniquingKeysWith: { first, _ in first })
  let kept = existingSource.map(existingFeatureNames) ?? [:]
  var names: [String: String] = [:]
  var taken = Set<String>()
  for feature in features {
    if let name = kept[feature.key], !taken.contains(name) {
      names[feature.key] = name
      taken.insert(name)
    }
  }
  for feature in features where names[feature.key] == nil {
    var base = featureConstantName(for: feature.key)
    if reservedWords.contains(base) { base += "_" }
    var name = base
    var suffix = 2
    while taken.contains(name) {
      name = base + String(suffix)
      suffix += 1
    }
    names[feature.key] = name
    taken.insert(name)
  }

  let source = list.change.map { "change \($0)" } ?? "release \(list.release.map(String.init) ?? "none")"
  var lines = [
    "// Generated by entitler generate. Do not edit.",
    "// Read from \(list.environment.name), \(list.track.name), \(source).",
    "",
    "import Entitler",
    "",
    "/// The features of your Entitler catalogue.",
  ]
  let access = accessLevel.rawValue
  guard !features.isEmpty else {
    lines.append("\(access) enum Features {}")
    return lines.joined(separator: "\n") + "\n"
  }
  lines.append("\(access) enum Features {")
  for (index, feature) in features.enumerated() {
    if index > 0 { lines.append("") }
    lines += documentation(of: feature).map { $0.isEmpty ? "  ///" : "  /// \($0)" }
    if feature.archived {
      lines.append("  @available(*, deprecated, message: \"Archived in Entitler.\")")
    }
    lines += declaration(
      of: feature, name: names[feature.key] ?? feature.key, access: access,
      leaves: leaves(of: feature, in: byKey))
  }
  lines.append("}")
  return lines.joined(separator: "\n") + "\n"
}

private func documentation(of feature: FeatureListing) -> [String] {
  var paragraphs = [[feature.name.isEmpty ? feature.key : feature.name]]
  let description = feature.description.split(separator: "\n", omittingEmptySubsequences: false)
    .map { $0.trimmingCharacters(in: .whitespaces) }
  if description.contains(where: { !$0.isEmpty }) { paragraphs.append(description) }
  if !feature.unit.isEmpty { paragraphs.append(["Counted in \(feature.unit)."]) }
  if feature.type == .group, !feature.includes.isEmpty {
    paragraphs.append(["Includes \(feature.includes.joined(separator: ", "))."])
  }
  return Array(paragraphs.joined(separator: [""]))
}

private func leaves(of group: FeatureListing, in features: [String: FeatureListing]) -> [String] {
  var leaves: [String] = []
  var visiting: Set<String> = [group.key]
  func visit(_ keys: [String]) {
    for key in keys {
      guard let feature = features[key], !visiting.contains(key) else { continue }
      if feature.type == .group {
        visiting.insert(key)
        visit(feature.includes)
        visiting.remove(key)
      } else if !leaves.contains(key) {
        leaves.append(key)
      }
    }
  }
  visit(group.includes)
  return leaves
}

private func declaration(of feature: FeatureListing, name: String, access: String, leaves: [String]) -> [String] {
  let head = "  \(access) static let \(name) = "
  let kind: String
  switch feature.type {
  case .boolean: kind = "OnOff"
  case .config: kind = "Config"
  case .metered: kind = "Metered"
  case .group: kind = "FeatureGroup"
  case .unknown: return [head + "\"\(feature.key)\""]
  }
  guard feature.type == .group else { return [head + "Feature<\(kind)>(\"\(feature.key)\")"] }
  let includes = "[" + leaves.map { "\"\($0)\"" }.joined(separator: ", ") + "]"
  let line = head + "Feature<\(kind)>(\"\(feature.key)\", includes: \(includes))"
  if line.count <= 100 { return [line] }
  let call = ["  \(access) static let \(name) = Feature<\(kind)>("]
  let argument = "    \"\(feature.key)\", includes: \(includes)"
  if argument.count <= 100 { return call + [argument, "  )"] }
  return call + ["    \"\(feature.key)\","] + ["    includes: ["]
    + leaves.map { "      \"\($0)\"," } + ["    ]", "  )"]
}
